debug: true

#队伍聊天频道设置
chat:
  format: "&b[队伍] %player_name%: %message%"
  #离开聊天频道的指令，不包含/pm
  leave-command:
    - /g
    - /l
    - /tc

#细节设置
settings:
  #强制玩家在大厅中生成
  force-spawn-lobby: true
  #队伍中最大人数
  max-player: 5
  #队伍最多可以合并的退伍数量
  max-join: 4

#游戏大厅
lobby:
  world: world
  x: -36
  y: 73
  z: -36
  yaw: 0.0
  pitch: 0.0

#游戏引擎
engine:
  #默认计时器
  default-timer:
    #默认前等待时间
    wait: 60
    #默认游戏时间
    game: 60
    #默认游戏结算时间
    finish: 10

#party指令本地化设置
commands:
  admin:
    party: 队伍
    games: 游戏
    player: 玩家
  party:
    invite: 邀请
    list: 成员
    dismiss: 解散
    kick: 踢出
    transfer: 转让
    join: 加入
    leave: 离开
    set: 设置
    create: 创建
    rename: 命名
  game:
    join: 加入
    ready: 准备
    unready: 取消准备
    rule: 规则
    finish: 结束
    set: 设置
    save: 保存
    reload: 重载
    leave: 离开

#party指令参数本地化设置
params:
  admin:
  party:
    set:
      friendlyFire: 队友误伤
  game:
    set:
      default-spawn: 默认出生点
      host-spawn: 主队出生点
      guest-spawn: 客队出生点

      wait-period: 等待时间
      game-period: 游戏时间
      finish-period: 结算时间
    rule:
      name: 规则

      item: 物品
      friendlyFire: 队友误伤

      enable: "允许"
      disable: "禁止"
      items:
        - 附魔金苹果
        - 金苹果
        - 鞘翅
        - 末影珍珠
        - 不死图腾
        - 熔岩桶
        - 凋灵骷髅头颅
        - 雕刻过的南瓜
        - 铁块
        - 铁锭
        - 狼刷怪蛋
        - TNT
